In [1]:
import pandas as pd
import numpy as np

In [2]:
objects = pd.read_csv('GroupingAndAggregationa/datasets/objects.csv')

In [3]:
object_group = objects.groupby('shape')
object_group.quantity.sum()

shape
circle        9
rectangle    36
square       13
Name: quantity, dtype: int64

In [8]:
array = objects.values
array.shape
array

array([['mirror', 'circle', 'silver', 1],
       ['wheel', 'circle', 'silver', 4],
       ['lemon', 'circle', 'yellow', 4],
       ['box', 'square', 'brown', 3],
       ['bread', 'square', 'white', 10],
       ['towel', 'rectangle', 'white', 2],
       ['laptop', 'rectangle', 'black', 1],
       ['pen', 'rectangle', 'blue', 7],
       ['bottle', 'rectangle', 'red', 6],
       ['biscuit', 'rectangle', 'brown', 20]], dtype=object)

In [11]:
array = array = objects.values.T.tolist()
array

[['mirror',
  'wheel',
  'lemon',
  'box',
  'bread',
  'towel',
  'laptop',
  'pen',
  'bottle',
  'biscuit'],
 ['circle',
  'circle',
  'circle',
  'square',
  'square',
  'rectangle',
  'rectangle',
  'rectangle',
  'rectangle',
  'rectangle'],
 ['silver',
  'silver',
  'yellow',
  'brown',
  'white',
  'white',
  'black',
  'blue',
  'red',
  'brown'],
 [1, 4, 4, 3, 10, 2, 1, 7, 6, 20]]

In [13]:
array_index = array[1:3]
array_index

[['circle',
  'circle',
  'circle',
  'square',
  'square',
  'rectangle',
  'rectangle',
  'rectangle',
  'rectangle',
  'rectangle'],
 ['silver',
  'silver',
  'yellow',
  'brown',
  'white',
  'white',
  'black',
  'blue',
  'red',
  'brown']]

In [14]:
index = pd.MultiIndex.from_arrays(array_index,names=['shape','colour'])

In [15]:
multi_data = pd.DataFrame({'object':array[0],'quantity':array[3]},index=index)

In [16]:
multi_data

                   object  quantity
shape     colour
circle    silver   mirror         1
          silver    wheel         4
          yellow    lemon         4
square    brown       box         3
          white     bread        10
rectangle white     towel         2
          black    laptop         1
          blue        pen         7
          red      bottle         6
          brown   biscuit        20

In [17]:
multi_data.groupby(level=['shape','colour']).sum()

                       object  quantity
shape     colour
circle    silver  mirrorwheel         5
          yellow        lemon         4
rectangle black        laptop         1
          blue            pen         7
          brown       biscuit        20
          red          bottle         6
          white         towel         2
square    brown           box         3
          white         bread        10

In [25]:
multi_data.groupby(level=['shape']).agg({'quantity' :[np.sum,np.min,np.max,np.mean]})

          quantity
               sum min max mean
shape
circle           9   1   4  3.0
rectangle       36   1  20  7.2
square          13   3  10  6.5

In [26]:
perfdata = pd.read_csv('filtering/datasets/StudentsPerformance.csv')

In [28]:
perfdata.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [30]:
genfilt = perfdata['gender'].isin(['female'])
genfilt.head(10)

0     True
1     True
2     True
3    False
4    False
5     True
6     True
7    False
8    False
9     True
Name: gender, dtype: bool

In [31]:
perfdata[genfilt].head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
9,female,group B,high school,free/reduced,none,38,60,50
12,female,group B,high school,standard,none,65,81,73
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
17,female,group B,some high school,free/reduced,none,18,32,28

In [32]:
perfdata[~genfilt].head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
13,male,group A,some college,standard,completed,78,72,70
16,male,group C,high school,standard,none,88,89,86
18,male,group C,master's degree,free/reduced,completed,46,42,46
20,male,group D,high school,standard,none,66,69,63

In [35]:
condition = perfdata['gender'].isin(['female']) & (perfdata['reading score'] > perfdata['writing score'])
perfdata[condition].head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
9,female,group B,high school,free/reduced,none,38,60,50
12,female,group B,high school,standard,none,65,81,73
17,female,group B,some high school,free/reduced,none,18,32,28
21,female,group B,some college,free/reduced,completed,65,75,70
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65

In [36]:
pdser = pd.Series(range(10))
pdser

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [37]:
pdser.where(pdser<3)

0    0.0
1    1.0
2    2.0
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
dtype: float64

In [40]:
pdser.mask(pdser<3,'x')

0    x
1    x
2    x
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: object

In [43]:
perfdata.drop_duplicates('race/ethnicity',keep=False)

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

In [45]:
dfs = pd.DataFrame({'quantity':[0,4,1,1,3,0,3]})
dfs.duplicated('quantity')

0    False
1    False
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [46]:
dfs.values

array([[0],
       [4],
       [1],
       [1],
       [3],
       [0],
       [3]])