In [1]:
import pandas as pd

In [5]:
myseries = pd.Series(index=[1,2,3],data=[1,2,3])

In [11]:
type(myseries.values)

numpy.ndarray

In [12]:
avocados = pd.read_csv('datasets/avocado.csv')

In [13]:
avocados

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico

In [14]:
avocados['test'] = 123

In [16]:
avocados

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,123
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,123

In [18]:
avocados.loc[-1] = ['99999','2018-01-07',1.65,12233.5,123.4,1.2,1.2,1.2,1.2,1.2,0.0,'organic',2018,'xyz',123]

In [19]:
avocados

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,123
-1,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123

In [20]:
avocados.index +=1

In [21]:
avocados

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
5,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18246,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18247,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18248,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123
18249,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,123
0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123

In [22]:
avocados = avocados.sort_index()

In [23]:
avocados

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18245,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,123
18246,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18247,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18248,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123
18249,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico,123

In [25]:
avocados = avocados.drop(avocados.index[-1])

In [26]:
avocados

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,6,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.0,organic,2018,WestTexNewMexico,123
18245,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,123
18246,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18247,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18248,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123

In [27]:
import numpy as np
testindex = np.arange(18249)

In [28]:
avocados.index= list(testindex)

In [29]:
avocados

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,6,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.0,organic,2018,WestTexNewMexico,123
18245,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,123
18246,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18247,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18248,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123

In [30]:
avocados = avocados.reset_index()

In [32]:
avocados

,index,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,18244,6,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.0,organic,2018,WestTexNewMexico,123
18245,18245,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,123
18246,18246,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18247,18247,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18248,18248,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123

In [33]:
avocados.drop(columns=['index'])

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,6,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.0,organic,2018,WestTexNewMexico,123
18245,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,123
18246,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18247,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18248,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123

In [35]:
avocados

,index,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,18244,6,2018-02-11,1.57,15986.17,1924.28,1368.32,0.00,12693.57,12437.35,256.22,0.0,organic,2018,WestTexNewMexico,123
18245,18245,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico,123
18246,18246,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico,123
18247,18247,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico,123
18248,18248,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico,123

In [40]:
avocados[['type','year']].tail(10)

          type  year
18239  organic  2018
18240  organic  2018
18241  organic  2018
18242  organic  2018
18243  organic  2018
18244  organic  2018
18245  organic  2018
18246  organic  2018
18247  organic  2018
18248  organic  2018

In [47]:
type(avocados.loc[:8])

pandas.DataFrame

In [48]:
avocados_new = avocados[(avocados['region'] == 'TotalUS') \
& (avocados['Date'] > '2018-01-01')]

In [49]:
avocados_new

,index,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
9091,9091,0,2018-03-25,1.03,43409835.75,14130799.10,12125711.42,758801.12,16394524.11,12540327.19,3544729.39,309467.53,conventional,2018,TotalUS,123
9092,9092,1,2018-03-18,1.05,41386314.12,13707389.51,11061051.69,645380.85,15972492.07,11712807.19,3988101.74,271583.14,conventional,2018,TotalUS,123
9093,9093,2,2018-03-11,1.09,40449603.12,14089091.05,10758039.45,707578.82,14894893.80,11392828.89,3229556.62,272508.29,conventional,2018,TotalUS,123
9094,9094,3,2018-03-04,1.07,40741214.05,14439547.46,11289307.37,571747.72,14440611.50,10832907.44,3339214.96,268489.10,conventional,2018,TotalUS,123
9095,9095,4,2018-02-25,1.06,40021528.76,13829857.87,10415463.59,724330.16,15051877.14,10666942.78,4081397.72,303536.64,conventional,2018,TotalUS,123
9096,9096,5,2018-02-18,1.08,36709887.49,13262751.42,10491918.44,552969.73,12402247.90,9023351.68,3151157.42,227738.80,conventional,2018,TotalUS,123
9097,9097,6,2018-02-11,0.97,43167806.09,15870677.70,11541844.87,652856.58,15102426.94,10844852.22,4023485.04,234089.68,conventional,2018,TotalUS,123
9098,9098,7,2018-02-04,0.87,62505646.52,21620180.90,20445501.03,1066830.22,19373134.37,13384586.80,5719096.61,269450.96,conventional,2018,TotalUS,123
9099,9099,8,2018-01-28,1.09,40171640.84,14551799.50,12119884.61,575974.74,12923981.99,9749412.19,3041125.42,133444.38,conventional,2018,TotalUS,123
9100,9100,9,2018-01-21,1.08,42939821.55,14218843.83,13929702.12,928815.12,13862460.48,9866218.28,3789722.90,206519.30,conventional,2018,TotalUS,123
9101,9101,10,2018-01-14,1.20,37299945.22,12600918.24,11866197.84,652808.40,12180020.74,8128241.88,3917569.95,134208.91,conventional,2018,TotalUS,123
9102,9102,11,2018-01-07,1.13,36703156.72,13730992.75,10781339.21,677714.86,11513109.90,8231766.23,3130919.10,150424.57,conventional,2018,TotalUS,123
18214,18214,0,2018-03-25,1.55,1559967.20,121007.94,342853.10,1070.24,1093861.09,902774.79,190941.84,144.46,organic,2018,TotalUS,123
18215,18215,1,2018-03-18,1.54,1675804.22,170801.85,444949.69,1045.38,1058651.50,837351.85,221129.46,170.19,organic,2018,TotalUS,123
18216,18216,2,2018-03-11,1.52,1664234.88,129169.72,408763.50,1401.87,1124621.50,944572.50,180049.00,0.00,organic,2018,TotalUS,123
18217,18217,3,2018-03-04,1.52,1634430.77,142345.03,390129.50,1225.97,1099871.68,831885.50,267818.31,167.87,organic,2018,TotalUS,123
18218,18218,4,2018-02-25,1.57,1459852.55,122912.97,340374.83,1063.32,994471.50,765056.82,229158.56,256.12,organic,2018,TotalUS,123
18219,18219,5,2018-02-18,1.52,1814929.97,246515.35,680037.45,1905.46,886241.96,783017.98,103184.01,39.97,organic,2018,TotalUS,123
18220,18220,6,2018-02-11,1.56,1317000.47,98465.26,270798.27,1839.80,945638.02,768242.42,177144.00,251.60,organic,2018,TotalUS,123
18221,18221,7,2018-02-04,1.53,1384683.41,117922.52,287724.61,1703.52,977084.84,774695.74,201878.69,510.41,organic,2018,TotalUS,123
18222,18222,8,2018-01-28,1.61,1336979.09,118616.17,280080.34,1270.61,936859.49,796104.27,140652.84,102.38,organic,2018,TotalUS,123
18223,18223,9,2018-01-21,1.63,1283987.65,108705.28,259172.13,1490.02,914409.26,710654.40,203526.59,228.27,organic,2018,TotalUS,123
18224,18224,10,2018-01-14,1.59,1476651.08,145680.62,323669.83,1580.01,1005593.78,858772.69,146808.97,12.12,organic,2018,TotalUS,123
18225,18225,11,2018-01-07,1.51,1517332.70,129541.43,296490.29,1289.07,1089861.24,915452.78,174381.57,26.89,organic,2018,TotalUS,123

In [50]:
avocados_new = avocados_new.sort_values(['Date'])

In [51]:
avocados_new

,index,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
9102,9102,11,2018-01-07,1.13,36703156.72,13730992.75,10781339.21,677714.86,11513109.90,8231766.23,3130919.10,150424.57,conventional,2018,TotalUS,123
18225,18225,11,2018-01-07,1.51,1517332.70,129541.43,296490.29,1289.07,1089861.24,915452.78,174381.57,26.89,organic,2018,TotalUS,123
18224,18224,10,2018-01-14,1.59,1476651.08,145680.62,323669.83,1580.01,1005593.78,858772.69,146808.97,12.12,organic,2018,TotalUS,123
9101,9101,10,2018-01-14,1.20,37299945.22,12600918.24,11866197.84,652808.40,12180020.74,8128241.88,3917569.95,134208.91,conventional,2018,TotalUS,123
9100,9100,9,2018-01-21,1.08,42939821.55,14218843.83,13929702.12,928815.12,13862460.48,9866218.28,3789722.90,206519.30,conventional,2018,TotalUS,123
18223,18223,9,2018-01-21,1.63,1283987.65,108705.28,259172.13,1490.02,914409.26,710654.40,203526.59,228.27,organic,2018,TotalUS,123
9099,9099,8,2018-01-28,1.09,40171640.84,14551799.50,12119884.61,575974.74,12923981.99,9749412.19,3041125.42,133444.38,conventional,2018,TotalUS,123
18222,18222,8,2018-01-28,1.61,1336979.09,118616.17,280080.34,1270.61,936859.49,796104.27,140652.84,102.38,organic,2018,TotalUS,123
9098,9098,7,2018-02-04,0.87,62505646.52,21620180.90,20445501.03,1066830.22,19373134.37,13384586.80,5719096.61,269450.96,conventional,2018,TotalUS,123
18221,18221,7,2018-02-04,1.53,1384683.41,117922.52,287724.61,1703.52,977084.84,774695.74,201878.69,510.41,organic,2018,TotalUS,123
9097,9097,6,2018-02-11,0.97,43167806.09,15870677.70,11541844.87,652856.58,15102426.94,10844852.22,4023485.04,234089.68,conventional,2018,TotalUS,123
18220,18220,6,2018-02-11,1.56,1317000.47,98465.26,270798.27,1839.80,945638.02,768242.42,177144.00,251.60,organic,2018,TotalUS,123
18219,18219,5,2018-02-18,1.52,1814929.97,246515.35,680037.45,1905.46,886241.96,783017.98,103184.01,39.97,organic,2018,TotalUS,123
9096,9096,5,2018-02-18,1.08,36709887.49,13262751.42,10491918.44,552969.73,12402247.90,9023351.68,3151157.42,227738.80,conventional,2018,TotalUS,123
9095,9095,4,2018-02-25,1.06,40021528.76,13829857.87,10415463.59,724330.16,15051877.14,10666942.78,4081397.72,303536.64,conventional,2018,TotalUS,123
18218,18218,4,2018-02-25,1.57,1459852.55,122912.97,340374.83,1063.32,994471.50,765056.82,229158.56,256.12,organic,2018,TotalUS,123
9094,9094,3,2018-03-04,1.07,40741214.05,14439547.46,11289307.37,571747.72,14440611.50,10832907.44,3339214.96,268489.10,conventional,2018,TotalUS,123
18217,18217,3,2018-03-04,1.52,1634430.77,142345.03,390129.50,1225.97,1099871.68,831885.50,267818.31,167.87,organic,2018,TotalUS,123
18216,18216,2,2018-03-11,1.52,1664234.88,129169.72,408763.50,1401.87,1124621.50,944572.50,180049.00,0.00,organic,2018,TotalUS,123
9093,9093,2,2018-03-11,1.09,40449603.12,14089091.05,10758039.45,707578.82,14894893.80,11392828.89,3229556.62,272508.29,conventional,2018,TotalUS,123
9092,9092,1,2018-03-18,1.05,41386314.12,13707389.51,11061051.69,645380.85,15972492.07,11712807.19,3988101.74,271583.14,conventional,2018,TotalUS,123
18215,18215,1,2018-03-18,1.54,1675804.22,170801.85,444949.69,1045.38,1058651.50,837351.85,221129.46,170.19,organic,2018,TotalUS,123
18214,18214,0,2018-03-25,1.55,1559967.20,121007.94,342853.10,1070.24,1093861.09,902774.79,190941.84,144.46,organic,2018,TotalUS,123
9091,9091,0,2018-03-25,1.03,43409835.75,14130799.10,12125711.42,758801.12,16394524.11,12540327.19,3544729.39,309467.53,conventional,2018,TotalUS,123

In [52]:
avocados_new_pivot = avocados_new.pivot(index='Date',columns='type',values='AveragePrice')

In [53]:
avocados_new_pivot

type        conventional  organic
Date
2018-01-07          1.13     1.51
2018-01-14          1.20     1.59
2018-01-21          1.08     1.63
2018-01-28          1.09     1.61
2018-02-04          0.87     1.53
2018-02-11          0.97     1.56
2018-02-18          1.08     1.52
2018-02-25          1.06     1.57
2018-03-04          1.07     1.52
2018-03-11          1.09     1.52
2018-03-18          1.05     1.54
2018-03-25          1.03     1.55

In [54]:
companies = ['Amazon','Apple']
ceos = ['jeffbezos','timcook']
comp_tup = list(zip(companies,ceos))

In [58]:
comp_df = pd.DataFrame(comp_tup,columns=['comp','ceo'])
comp_df

     comp        ceo
0  Amazon  jeffbezos
1   Apple    timcook

In [74]:
tes = avocados.iloc[:]

In [75]:
tes

,index,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123
5,5,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,123

In [80]:
tes.drop(tes.index[5])

,index,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region,test
0,0,99999,2018-01-07,1.65,12233.50,123.40,1.20,1.20,1.20,1.20,1.20,0.0,organic,2018,xyz,123
1,1,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,123
2,2,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,123
3,3,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,123
4,4,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,123